-- ==========================================================
-- Project     : Digital Health Vault
-- Module      : Master
-- Version     : V0026
-- Description : Seed Data in Role Permission Table
-- Author      : Akhil Tandrotu
-- Created On  : 2026-07-20
-- ==========================================================

INSERT INTO master.role_permission
(
    role_code,
    permission_code,
    created_by
)
VALUES

-- ==========================
-- PATIENT
-- ==========================

('PATIENT','AUTH:LOGIN','FLYWAY'),
('PATIENT','AUTH:REGISTER','FLYWAY'),
('PATIENT','AUTH:LOGOUT','FLYWAY'),
('PATIENT','PROFILE:VIEW','FLYWAY'),
('PATIENT','PROFILE:UPDATE','FLYWAY'),
('PATIENT','MEDICAL_RECORD:VIEW','FLYWAY'),
('PATIENT','MEDICAL_RECORD:CREATE','FLYWAY'),
('PATIENT','MEDICAL_RECORD:UPDATE','FLYWAY'),

-- ==========================
-- DOCTOR
-- ==========================

('DOCTOR','AUTH:LOGIN','FLYWAY'),
('DOCTOR','AUTH:LOGOUT','FLYWAY'),
('DOCTOR','PROFILE:VIEW','FLYWAY'),
('DOCTOR','PROFILE:UPDATE','FLYWAY'),
('DOCTOR','MEDICAL_RECORD:VIEW','FLYWAY'),
('DOCTOR','MEDICAL_RECORD:CREATE','FLYWAY'),
('DOCTOR','MEDICAL_RECORD:UPDATE','FLYWAY'),

-- ==========================
-- HOSPITAL_ADMIN
-- ==========================

('HOSPITAL_ADMIN','AUTH:LOGIN','FLYWAY'),
('HOSPITAL_ADMIN','AUTH:LOGOUT','FLYWAY'),
('HOSPITAL_ADMIN','PROFILE:VIEW','FLYWAY'),
('HOSPITAL_ADMIN','PROFILE:UPDATE','FLYWAY'),
('HOSPITAL_ADMIN','MEDICAL_RECORD:VIEW','FLYWAY'),
('HOSPITAL_ADMIN','MEDICAL_RECORD:CREATE','FLYWAY'),
('HOSPITAL_ADMIN','MEDICAL_RECORD:UPDATE','FLYWAY'),
('HOSPITAL_ADMIN','MEDICAL_RECORD:DELETE','FLYWAY'),

-- ==========================
-- LAB_ADMIN
-- ==========================

('LAB_ADMIN','AUTH:LOGIN','FLYWAY'),
('LAB_ADMIN','AUTH:LOGOUT','FLYWAY'),
('LAB_ADMIN','PROFILE:VIEW','FLYWAY'),
('LAB_ADMIN','MEDICAL_RECORD:VIEW','FLYWAY'),
('LAB_ADMIN','MEDICAL_RECORD:CREATE','FLYWAY'),

-- ==========================
-- SUPPORT
-- ==========================

('SUPPORT','AUTH:LOGIN','FLYWAY'),
('SUPPORT','AUTH:LOGOUT','FLYWAY'),
('SUPPORT','PROFILE:VIEW','FLYWAY'),
('SUPPORT','USER:LOCK','FLYWAY'),
('SUPPORT','USER:UNLOCK','FLYWAY'),
('SUPPORT','AUDIT:VIEW','FLYWAY'),

-- ==========================
-- TESTER
-- ==========================

('TESTER','AUTH:LOGIN','FLYWAY'),
('TESTER','AUTH:REGISTER','FLYWAY'),
('TESTER','AUTH:LOGOUT','FLYWAY'),
('TESTER','PROFILE:VIEW','FLYWAY'),
('TESTER','PROFILE:UPDATE','FLYWAY'),
('TESTER','MEDICAL_RECORD:VIEW','FLYWAY'),
('TESTER','MEDICAL_RECORD:CREATE','FLYWAY'),
('TESTER','MEDICAL_RECORD:UPDATE','FLYWAY'),
('TESTER','MEDICAL_RECORD:DELETE','FLYWAY'),
('TESTER','USER:LOCK','FLYWAY'),
('TESTER','USER:UNLOCK','FLYWAY'),
('TESTER','AUDIT:VIEW','FLYWAY'),

-- ==========================
-- DEVELOPER
-- ==========================

('DEVELOPER','AUTH:LOGIN','FLYWAY'),
('DEVELOPER','AUTH:REGISTER','FLYWAY'),
('DEVELOPER','AUTH:LOGOUT','FLYWAY'),
('DEVELOPER','PROFILE:VIEW','FLYWAY'),
('DEVELOPER','PROFILE:UPDATE','FLYWAY'),
('DEVELOPER','MEDICAL_RECORD:VIEW','FLYWAY'),
('DEVELOPER','MEDICAL_RECORD:CREATE','FLYWAY'),
('DEVELOPER','MEDICAL_RECORD:UPDATE','FLYWAY'),
('DEVELOPER','MEDICAL_RECORD:DELETE','FLYWAY'),
('DEVELOPER','USER:LOCK','FLYWAY'),
('DEVELOPER','USER:UNLOCK','FLYWAY'),
('DEVELOPER','AUDIT:VIEW','FLYWAY'),

-- ==========================
-- SYSTEM_ADMIN
-- ==========================

('SYSTEM_ADMIN','AUTH:LOGIN','FLYWAY'),
('SYSTEM_ADMIN','AUTH:REGISTER','FLYWAY'),
('SYSTEM_ADMIN','AUTH:LOGOUT','FLYWAY'),
('SYSTEM_ADMIN','PROFILE:VIEW','FLYWAY'),
('SYSTEM_ADMIN','PROFILE:UPDATE','FLYWAY'),
('SYSTEM_ADMIN','MEDICAL_RECORD:VIEW','FLYWAY'),
('SYSTEM_ADMIN','MEDICAL_RECORD:CREATE','FLYWAY'),
('SYSTEM_ADMIN','MEDICAL_RECORD:UPDATE','FLYWAY'),
('SYSTEM_ADMIN','MEDICAL_RECORD:DELETE','FLYWAY'),
('SYSTEM_ADMIN','USER:LOCK','FLYWAY'),
('SYSTEM_ADMIN','USER:UNLOCK','FLYWAY'),
('SYSTEM_ADMIN','AUDIT:VIEW','FLYWAY');